#!/bin/bash

#
# Automaçao DNS
#
# Mylena Torquato
#
# CVS $Header$

shopt -s -o nounset

x="continuar"
pasta="/etc/bind"
conf_default="named.conf.default-zones"
ip="/etc/network/interfaces"
resolv="/etc/resolv.conf"

menu(){
  clear

  while true
  do

    echo -e "-/-/-/-/-/ MENU PRINCIPAL -/-/-/-/-/"
    echo -e "1. MENU DNS"
    echo -e "2. MENU APACHE"
    echo -e "3. SAIR"
    echo -e "Selecione a opção desejada: "
    read opcao

    case $opcao in

      1)
        echo "Direcionando para o menu do DNS"
        dns
        ;;

      2)
        echo "Direcionando para o menu do Apache"
        apache
        ;;

      3)
        echo "Saindo do programa."
        break
        ;;

      *)
        echo "Selecione uma opção válida"
        menu
        ;;

    esac
  done
}

dns(){
  clear

  while true
  do

    echo -e "            MENU            "
    echo -e "1. Configuração de IP"
    echo -e ""
    echo -e "2. Configuração de Sources List"
    echo -e ""
    echo -e "3. Instalar"
    echo -e ""
    echo -e "4. Desinstalar"
    echo -e ""
    echo -e "5. Iniciar"
    echo -e ""
    echo -e "6. Parar"
    echo -e ""
    echo -e "7. Criar e configurar zonas"
    echo -e ""
    echo -e "8. Editar"
    echo -e ""
    echo -e "9. Excluir"
    echo -e ""
    echo -e "10. Informações"
    echo -e ""
    echo -e "11. Sair"
    echo -e ""
    echo -e "Selecione a opção deseja"
    read option

    case $option in

      1)
        echo "Escolheu 1"
        echo "Informe o IP do dns-server"
        read dns_server

        sed -i '10i\nameserver $dns_server' /etc/resolv.conf
        echo "Qual é a sua máscara de rede?: "
        read mask
        echo "Qual é o seu gateway?: "
        read gate
        echo "Em qual interface o DNS vai funcionar? (ex:enp0s3): "
        read interface

        {
          if [[ "$gate" == "0" ]]; then
            sed -i "s|iface $interface inet dhcp|iface $interface inet static \naddress $dns_server \nnetmask $mask|" "/etc/network/interfaces"
          else
            sed -i "s|iface $interface inet dhcp|iface $interface inet static \naddress $dns_server \nnetmask $mask \ngateway $gate|" "/etc/network/interfaces"
          fi
        } >>"/etc/network/interfaces"

        echo "IP configurado !"
        ;;

      2)
        echo "Escolheu 2"
        echo "Atualizando Source List"
        echo "$repo_line" > "$sources_list"
        ;;

      3)
        echo "Escolheu 3"
        apt-get install bind9
        sleep 3
        ;;

      4)
        echo "Escolheu 4"
        echo "Você escolheu DESINSTALAR O SERVIDOR!!"
        echo "Você tem certeza disso?? (S / N): "
        read resp
        if [[ "$resp" == "S" || "$resp" == "s" ]]; then
          apt-get remove bind9
        else
          break
        fi
        ;;

      5)
        echo "Escolheu 5"
        echo "Iniciando servidor DNS"
        systemctl start bind9
        ;;

      6)
        echo "Escolheu 6"
        echo "Você escolheu PARAR O SERVIDOR DNS, você tem certeza disso? (S / N): "
        read ans
        if [[ "$ans" == "S" || "$ans" == "s" ]]; then
          systemctl stop bind9
        else
          break
        fi
        ;;

      7)
        echo "Escolheu 7"
        # Criando zonas
        while [[ loop==true ]]; do
          echo "Qual é o nome da zona que você deseja criar?:* (google, youtube, npc...)"
          read zone
          echo "Final da zona que deseja colocar:* (.local, .com, ...)"
          read end
          # named.conf.default-zones
          zona_compl="$zone$end"
          zona_local="$pasta/db.$zone"
          {
            echo "zone @" {
            echo "      type master;"
            echo "      file =;"
            echo -e "};\n"

            sed -i 's/@/"x"/g' $conf_default
            sed -i "s|x|$zona_compl|g" $conf_default
            sed -i 's/=/"+"/g' $conf_default
            sed -i "s|+|$zona_local|g" $conf_default
          } >>"$conf_default"

          echo "Início da zona que seja colocar:* (www, ns1, ...)"
          read inin
          echo "IP do server WEB:* "
          read ip_servico
          # Criando db
          localhost="ns1.$zone"
          touch "$zona_local"
          {
            echo -e "; BIND reverse data file for empty rfc1918 zone\n;\n; DO NOT EDIT THIS FILE - it is used for multiple zones.\n; Instead, copy it, edit named.conf, and use that copy.\n;\n=TTL 86400\n@ >
            echo "$inin     IN      A       $ip_servico"
            sed -i "s|=|$|" "$pasta/db.$zone"
            sed -i "s|localhost|$localhost|g" "$pasta/db.$zone"
          } >>"$pasta/db.$zone"

          echo "Deseja adicionar mais uma zona? (S / N)"
          read verif
          while [[ "$verif" == "S" || "$verif" == "s" ]]; do
            echo "Início da zona que seja colocar:* (www, ns1, ...)"
            read start
            echo "IP do server WEB:* "
            read ip_servico
            {
              echo "$start    IN      A       $ip_servico"
            } >>"$pasta/db.$zone"

            echo "Deseja adicionar mais um início de zona? (S / N)"
            read verif
          done

          echo "Deseja adicionar mais uma zona? (S / N)"
          read verificar
          if [[ "$verif" == "N" || "$verif" == "n" ]]; then
            break
          fi
        done
        ;;

      8)
        echo "Escolheu 8"
        ;;

      9)
        echo "Escolheu 9"
        ;;

      10)
        echo "Escolheu 10"
        echo "Qual arquivo você deseja checar?: "
        read check
        ;;

      11)
        echo "Escolheu 11"
        ;;

      *)
        echo "Opção invalida"
        ;;

    esac
  done
}

apache(){
  clear

  while true
  do
  done
}

# Valida user

if [[ "$EUID" -ne 0 ]]; then
  echo "Necessario permissão de root"
else
  apt-get update -y && apt-get upgrade -y
  menu
fi
